### PR TITLE
Adding theme in the main page

### PR DESCRIPTION
**Pull request by sdmg15**

### CODE REVIEW

**Comment by sdmg15** [comment]
I think just like intended 😄 
Haven't you merge and test?

**Comment by valerymelou** [comment]
I changed it a little for semantics. Check again if you agree we can merge it.

**Comment by sdmg15** [comment]
Okay let me check

**Comment by sdmg15** [comment]
@valerymelou Any deployment descriptor ? I merge and pulled the changes in the server but nothing has change till now. Thanks

**Comment by valerymelou** [comment]
You have to reload the app by restarting the Gunicorn service.

**Comment by sdmg15** [comment]
Please let me have the command

**Comment by valerymelou** [comment]
Sorry, typing from a mobile phone. I assumed you would look.

`systemctl restart gunicorn.service`

**Pull request merged**
